### PR TITLE
 installation of libmagic fixed

### PR DESCRIPTION
**Pull request by Graur**
Trying to fix this error message:  /bin/sh: apt-get: not found

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 I think this change might help. Our builds are still [broken](https://github.com/objectionary/eo/issues/804)

**Comment by yegor256** [comment]
@g4s8 please, merge this

**Comment by g4s8** [comment]
@Graur thanks for PR. Is it build dependency or runtime one? If it's built dep, then this dockerfile already has a section for build does. If it's runtime dep, you can add it next line after build deps. Also, you don't need apk update flag, since it's updated on first command in this RUN

**Comment by Graur** [comment]
@g4s8 Thanks! Indeed, as I know it's a build dependency. Please, have a look

**Review by g4s8 — APPROVED** [review]

**Pull request merged**
